"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { QRCodeSVG } from "qrcode.react";
import { AppHeader } from "@/components/layout/app-header";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useMembers } from "@/hooks/use-members";
import { useMedicines } from "@/hooks/use-medicines";
import {
  Heart,
  AlertTriangle,
  Share2,
  Pencil,
  Plus,
  QrCode,
  X,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";

function calculateAge(dateOfBirth: string): number | null {
  if (!dateOfBirth) return null;
  const birth = new Date(dateOfBirth);
  const today = new Date();
  let age = today.getFullYear() - birth.getFullYear();
  const monthDiff = today.getMonth() - birth.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
    age--;
  }
  return age;
}

function formatGender(gender: string): string {
  if (!gender) return "—";
  return gender.charAt(0).toUpperCase() + gender.slice(1);
}

function formatRelation(relation: string): string {
  if (relation === "self") return "You";
  return relation.charAt(0).toUpperCase() + relation.slice(1);
}

export default function EmergencyCardPage() {
  const router = useRouter();
  const { members, isLoading: membersLoading, deleteMember } = useMembers();
  const [selectedMemberId, setSelectedMemberId] = useState<string>("");
  const [showQR, setShowQR] = useState(false);

  // Pick the active member: explicitly selected → self → first available
  const selfMember = useMemo(() => {
    if (selectedMemberId) {
      const found = members.find((m) => m.id === selectedMemberId);
      if (found) return found;
    }
    return (
      members.find((m) => m.relation === "self") || members[0] || undefined
    );
  }, [members, selectedMemberId]);

  const { activeMedicines, isLoading: medsLoading } = useMedicines(
    selfMember?.id
  );

  const age = selfMember?.date_of_birth
    ? calculateAge(selfMember.date_of_birth)
    : null;

  const handleShareCard = async () => {
    if (!selfMember) return;

    const lines: string[] = [
      "🚨 EMERGENCY HEALTH CARD",
      "",
      `Name: ${selfMember.name}`,
    ];

    if (selfMember.blood_group) lines.push(`Blood Group: ${selfMember.blood_group}`);
    if (selfMember.gender) lines.push(`Gender: ${formatGender(selfMember.gender)}`);
    if (age !== null) lines.push(`Age: ${age} years`);

    if (selfMember.allergies?.length) {
      lines.push("", `⚠️ ALLERGIES: ${selfMember.allergies.join(", ")}`);
    }

    if (selfMember.chronic_conditions?.length) {
      lines.push("", `Chronic Conditions: ${selfMember.chronic_conditions.join(", ")}`);
    }

    if (activeMedicines.length > 0) {
      const medList = activeMedicines
        .map((m) => `${m.name}${m.dosage ? ` (${m.dosage})` : ""}`)
        .join(", ");
      lines.push("", `Current Medicines: ${medList}`);
    }

    if (selfMember.emergency_contact_name || selfMember.emergency_contact_phone) {
      lines.push(
        "",
        `📞 Emergency Contact: ${selfMember.emergency_contact_name || "—"} ${selfMember.emergency_contact_phone || ""}`.trim()
      );
    }

    if (selfMember.abha_number) lines.push("", `ABHA ID: ${selfMember.abha_number}`);

    lines.push("", "—", "Generated by MediFamily — https://medifamily.in");

    const text = lines.join("\n");

    try {
      if (navigator.share) {
        await navigator.share({
          title: `${selfMember.name} — Emergency Health Card`,
          text,
        });
      } else {
        await navigator.clipboard.writeText(text);
        toast.success("Emergency card copied to clipboard");
      }
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") return;
      toast.error("Failed to share");
    }
  };

  const handleDelete = async () => {
    if (!selfMember) return;
    if (
      !confirm(
        `Delete ${selfMember.name}'s emergency card? This will remove their profile.`
      )
    )
      return;
    try {
      await deleteMember(selfMember.id);
      toast.success(`${selfMember.name}'s card deleted`);
      // Pick another member if any remain
      const next = members.find((m) => m.id !== selfMember.id);
      if (next) {
        setSelectedMemberId(next.id);
      } else {
        router.replace("/family");
      }
    } catch (err) {
      console.error("Delete failed:", err);
      toast.error(
        err instanceof Error ? err.message : "Failed to delete profile"
      );
    }
  };

  // ─── Loading state ───────────────────────────────────────────────
  if (membersLoading || medsLoading) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        <AppHeader title="Emergency Card" showBack />
        <div className="flex-1 flex items-center justify-center">
          <div className="animate-pulse text-muted-foreground">Loading...</div>
        </div>
      </div>
    );
  }

  // ─── Empty state ─────────────────────────────────────────────────
  if (members.length === 0) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        <AppHeader title="Emergency Card" showBack />
        <div className="flex-1 flex flex-col items-center justify-center px-6 text-center">
          <div className="rounded-full bg-red-50 dark:bg-red-950/30 p-5 mb-4">
            <Heart className="h-10 w-10 text-red-500" />
          </div>
          <h3 className="text-lg font-bold mb-1.5">No Emergency Card Yet</h3>
          <p className="text-sm text-muted-foreground mb-6 max-w-xs">
            Add your health profile so doctors can access critical info instantly in emergencies.
          </p>
          <Button
            size="lg"
            className="bg-red-600 hover:bg-red-700 text-white"
            onClick={() => router.push("/family/add")}
          >
            <Plus className="h-4 w-4 mr-2" />
            Create Emergency Card
          </Button>
        </div>
      </div>
    );
  }

  if (!selfMember) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        <AppHeader title="Emergency Card" showBack />
        <div className="flex-1 flex items-center justify-center">
          <div className="animate-pulse text-muted-foreground">Loading...</div>
        </div>
      </div>
    );
  }

  const initial = selfMember.name?.charAt(0)?.toUpperCase() || "?";
  const hasAllergies = selfMember.allergies && selfMember.allergies.length > 0;

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <AppHeader title="Emergency Card" showBack />

      <main className="flex-1 px-4 py-4 pb-32 space-y-4 max-w-lg mx-auto w-full">
        {/* ─── Member Pills (only if 2+ members) ───────────────────── */}
        {members.length > 1 && (
          <div className="flex gap-2 overflow-x-auto -mx-1 px-1 pb-1 no-scrollbar">
            {members.map((m) => {
              const active = m.id === selectedMemberId;
              const memberInitial = m.name?.charAt(0)?.toUpperCase() || "?";
              return (
                <button
                  key={m.id}
                  onClick={() => setSelectedMemberId(m.id)}
                  className={`flex items-center gap-2 shrink-0 rounded-full pl-1 pr-3 py-1 border transition-all ${
                    active
                      ? "bg-red-600 border-red-600 text-white shadow-md scale-105"
                      : "bg-background border-border hover:border-red-300"
                  }`}
                >
                  <div
                    className={`h-7 w-7 rounded-full flex items-center justify-center text-xs font-bold ${
                      active
                        ? "bg-white text-red-600"
                        : "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400"
                    }`}
                  >
                    {memberInitial}
                  </div>
                  <span className="text-xs font-medium whitespace-nowrap">
                    {m.name}
                  </span>
                </button>
              );
            })}
          </div>
        )}

        {/* ─── HERO: Critical Identity Card (tap to show QR) ──────── */}
        <Card
          onClick={() => setShowQR(true)}
          className="overflow-hidden border-2 border-red-500 shadow-lg cursor-pointer hover:shadow-xl transition-shadow active:scale-[0.99]"
        >
          {/* Red header with SOS branding */}
          <div className="bg-gradient-to-r from-red-600 to-red-700 px-4 py-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="h-7 w-7 rounded-full bg-white/20 flex items-center justify-center">
                <Heart className="h-4 w-4 text-white fill-white" />
              </div>
              <span className="text-white font-bold text-xs tracking-widest uppercase">
                Emergency Health Card
              </span>
            </div>
            <div className="h-7 w-7 rounded-full bg-white/20 flex items-center justify-center">
              <QrCode className="h-3.5 w-3.5 text-white" />
            </div>
          </div>

          <CardContent className="p-0">
            {/* Identity row */}
            <div className="flex items-center gap-3 px-4 py-4 border-b">
              <div className="h-14 w-14 rounded-full bg-gradient-to-br from-red-500 to-red-700 flex items-center justify-center text-white text-xl font-bold shadow-md shrink-0">
                {initial}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xl font-bold leading-tight truncate">
                  {selfMember.name}
                </p>
                <div className="flex items-center gap-2 mt-0.5 text-xs text-muted-foreground">
                  <span>{formatRelation(selfMember.relation)}</span>
                  {age !== null && (
                    <>
                      <span>•</span>
                      <span>{age} yrs</span>
                    </>
                  )}
                  {selfMember.gender && (
                    <>
                      <span>•</span>
                      <span>{formatGender(selfMember.gender)}</span>
                    </>
                  )}
                </div>
              </div>
            </div>

            {/* MASSIVE blood group display */}
            <div className="px-4 py-5 bg-red-50 dark:bg-red-950/20 flex items-center gap-4">
              <div className="h-16 w-16 rounded-2xl bg-red-600 flex items-center justify-center shadow-lg">
                <span className="text-white text-2xl font-black">
                  {selfMember.blood_group || "?"}
                </span>
              </div>
              <div>
                <p className="text-[10px] uppercase tracking-widest text-red-700 dark:text-red-400 font-bold">
                  Blood Group
                </p>
                <p className="text-sm font-medium mt-0.5">
                  {selfMember.blood_group
                    ? "Tap card to show QR code"
                    : "Not set — tap edit to add"}
                </p>
              </div>
            </div>

            {/* CRITICAL: Allergies — only render if present, in a bright alert box */}
            {hasAllergies && (
              <div className="px-4 py-4 bg-red-50 dark:bg-red-950/30 border-t-2 border-red-300 dark:border-red-800">
                <div className="flex items-center gap-2 mb-2">
                  <AlertTriangle className="h-5 w-5 text-red-600 fill-red-100" />
                  <h3 className="text-sm font-bold text-red-700 dark:text-red-400 uppercase tracking-wide">
                    ⚠ Allergies
                  </h3>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {selfMember.allergies?.map((allergy, i) => (
                    <span
                      key={i}
                      className="px-3 py-1 rounded-full bg-red-600 text-white text-xs font-semibold"
                    >
                      {allergy}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Compact action row — Edit + Delete */}
        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={() => router.push(`/family/${selfMember.id}/edit`)}
            className="flex items-center justify-center gap-2 h-11 rounded-xl border border-border bg-background hover:bg-muted/50 text-sm font-medium transition"
          >
            <Pencil className="h-4 w-4" />
            Edit Profile
          </button>
          <button
            onClick={handleDelete}
            className="flex items-center justify-center gap-2 h-11 rounded-xl border border-red-200 dark:border-red-900 bg-red-50 dark:bg-red-950/20 hover:bg-red-100 dark:hover:bg-red-950/40 text-sm font-medium text-red-600 transition"
          >
            <Trash2 className="h-4 w-4" />
            Delete
          </button>
        </div>

        {/* Branding footer */}
        <div className="text-center pt-2">
          <p className="text-[11px] text-muted-foreground">
            Powered by{" "}
            <span className="font-semibold text-red-600">MediFamily</span> ❤️
          </p>
        </div>
      </main>

      {/* ─── Sticky Share Button ──────────────────────────────────── */}
      <div className="fixed bottom-20 left-0 right-0 px-4 z-10 pointer-events-none">
        <div className="max-w-lg mx-auto pointer-events-auto">
          <Button
            onClick={handleShareCard}
            className="w-full h-12 bg-red-600 hover:bg-red-700 text-white shadow-2xl shadow-red-600/30 rounded-full font-semibold"
          >
            <Share2 className="h-5 w-5 mr-2" />
            Share Emergency Card
          </Button>
        </div>
      </div>

      {/* ─── QR Code Modal ────────────────────────────────────────── */}
      {showQR && (
        <div
          onClick={() => setShowQR(false)}
          className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-200"
        >
          <div
            onClick={(e) => e.stopPropagation()}
            className="relative bg-white dark:bg-zinc-900 rounded-3xl p-6 max-w-sm w-full shadow-2xl animate-in zoom-in-95 duration-200"
          >
            {/* Close button */}
            <button
              onClick={() => setShowQR(false)}
              className="absolute top-3 right-3 h-9 w-9 rounded-full bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 flex items-center justify-center transition"
              aria-label="Close"
            >
              <X className="h-4 w-4" />
            </button>

            {/* Header */}
            <div className="text-center mb-4">
              <div className="inline-flex items-center gap-1.5 mb-2">
                <Heart className="h-4 w-4 text-red-600 fill-red-600" />
                <span className="text-[10px] uppercase tracking-widest font-bold text-red-600">
                  Emergency Card
                </span>
              </div>
              <h2 className="text-xl font-bold">{selfMember.name}</h2>
              <p className="text-xs text-muted-foreground mt-0.5">
                {[
                  selfMember.blood_group,
                  age !== null ? `${age} yrs` : null,
                  selfMember.gender ? formatGender(selfMember.gender) : null,
                ]
                  .filter(Boolean)
                  .join(" · ")}
              </p>
            </div>

            {/* QR code */}
            <div className="bg-white p-4 rounded-2xl border-2 border-red-100 mb-4 flex items-center justify-center">
              <QRCodeSVG
                value={(() => {
                  const lines = [
                    `Name: ${selfMember.name}`,
                    selfMember.blood_group ? `Blood: ${selfMember.blood_group}` : "",
                    age !== null ? `Age: ${age}` : "",
                    selfMember.gender ? `Gender: ${formatGender(selfMember.gender)}` : "",
                    selfMember.allergies?.length
                      ? `Allergies: ${selfMember.allergies.join(", ")}`
                      : "",
                    selfMember.chronic_conditions?.length
                      ? `Conditions: ${selfMember.chronic_conditions.join(", ")}`
                      : "",
                    activeMedicines.length > 0
                      ? `Medicines: ${activeMedicines
                          .map((m) => m.name + (m.dosage ? ` (${m.dosage})` : ""))
                          .join(", ")}`
                      : "",
                    selfMember.emergency_contact_phone
                      ? `Contact: ${selfMember.emergency_contact_name || ""} ${selfMember.emergency_contact_phone}`.trim()
                      : "",
                  ]
                    .filter(Boolean)
                    .join("\n");
                  return `MEDIFAMILY EMERGENCY\n\n${lines}`;
                })()}
                size={240}
                level="M"
                marginSize={2}
              />
            </div>

            {/* Helper text */}
            <p className="text-center text-xs text-muted-foreground mb-3">
              Show this QR code to medical staff in emergencies
            </p>

            {/* Share button */}
            <Button
              onClick={() => {
                setShowQR(false);
                handleShareCard();
              }}
              className="w-full bg-red-600 hover:bg-red-700 text-white"
            >
              <Share2 className="h-4 w-4 mr-2" />
              Share as Text
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

