"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { QRCodeSVG } from "qrcode.react";
import { AppHeader } from "@/components/layout/app-header";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useMembers } from "@/hooks/use-members";
import { useMedicines } from "@/hooks/use-medicines";
import {
  Heart,
  AlertTriangle,
  Share2,
  Pencil,
  Plus,
  QrCode,
  X,
  Pill,
  Phone,
  Shield,
} from "lucide-react";
import { toast } from "sonner";

function calculateAge(dateOfBirth: string): number | null {
  if (!dateOfBirth) return null;
  const birth = new Date(dateOfBirth);
  const today = new Date();
  let age = today.getFullYear() - birth.getFullYear();
  const monthDiff = today.getMonth() - birth.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
    age--;
  }
  return age;
}

function formatGender(gender: string): string {
  if (!gender) return "";
  return gender.charAt(0).toUpperCase() + gender.slice(1);
}

function formatRelation(relation: string): string {
  if (relation === "self") return "You";
  return relation.charAt(0).toUpperCase() + relation.slice(1);
}

export default function EmergencyCardPage() {
  const router = useRouter();
  const { members, isLoading: membersLoading } = useMembers();
  const [selectedMemberId, setSelectedMemberId] = useState<string>("");
  const [showQR, setShowQR] = useState(false);

  const activeMember = useMemo(() => {
    if (selectedMemberId) {
      const found = members.find((m) => m.id === selectedMemberId);
      if (found) return found;
    }
    return members.find((m) => m.relation === "self") || members[0] || undefined;
  }, [members, selectedMemberId]);

  const { activeMedicines, isLoading: medsLoading } = useMedicines(activeMember?.id);

  const age = activeMember?.date_of_birth ? calculateAge(activeMember.date_of_birth) : null;

  const buildShareText = () => {
    if (!activeMember) return "";
    const lines: string[] = [
      "EMERGENCY HEALTH CARD",
      "",
      `Name: ${activeMember.name}`,
    ];
    if (activeMember.blood_group) lines.push(`Blood Group: ${activeMember.blood_group}`);
    if (activeMember.gender) lines.push(`Gender: ${formatGender(activeMember.gender)}`);
    if (age !== null) lines.push(`Age: ${age} years`);
    if (activeMember.allergies?.length) {
      lines.push("", `ALLERGIES: ${activeMember.allergies.join(", ")}`);
    }
    if (activeMember.chronic_conditions?.length) {
      lines.push("", `CONDITIONS: ${activeMember.chronic_conditions.join(", ")}`);
    }
    if (activeMedicines.length > 0) {
      lines.push(
        "",
        "CURRENT MEDICINES:",
        ...activeMedicines.map(
          (m) => `  ${m.name}${m.dosage ? ` (${m.dosage})` : ""}${m.frequency ? ` - ${m.frequency.replace("_", " ")}` : ""}`
        )
      );
    }
    if (activeMember.emergency_contact_phone) {
      lines.push(
        "",
        `EMERGENCY CONTACT: ${activeMember.emergency_contact_name || "Contact"} - ${activeMember.emergency_contact_phone}`
      );
    }
    if (activeMember.abha_number) lines.push("", `ABHA ID: ${activeMember.abha_number}`);
    lines.push("", "---", "Generated by MediFamily | medifamily.in");
    return lines.join("\n");
  };

  const handleShareCard = async () => {
    const text = buildShareText();
    if (!text) return;
    try {
      if (navigator.share) {
        await navigator.share({ title: `Emergency Card - ${activeMember!.name}`, text });
      } else {
        await navigator.clipboard.writeText(text);
        toast.success("Emergency card copied to clipboard");
      }
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") return;
      toast.error("Failed to share");
    }
  };

  // Loading
  if (membersLoading || medsLoading) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        <AppHeader title="Emergency Card" showBack />
        <div className="flex-1 flex items-center justify-center">
          <div className="animate-pulse text-muted-foreground">Loading...</div>
        </div>
      </div>
    );
  }

  // Empty
  if (members.length === 0) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        <AppHeader title="Emergency Card" showBack />
        <div className="flex-1 flex flex-col items-center justify-center px-6 text-center">
          <div className="rounded-full bg-red-50 dark:bg-red-950/30 p-5 mb-4">
            <Heart className="h-10 w-10 text-red-500" />
          </div>
          <h3 className="text-lg font-bold mb-1.5">No Emergency Card Yet</h3>
          <p className="text-sm text-muted-foreground mb-6 max-w-xs">
            Add your health profile so doctors can access critical info instantly in emergencies.
          </p>
          <Button
            size="lg"
            className="bg-red-600 hover:bg-red-700 text-white"
            onClick={() => router.push("/family/add")}
          >
            <Plus className="h-4 w-4 mr-2" />
            Create Emergency Card
          </Button>
        </div>
      </div>
    );
  }

  if (!activeMember) return null;

  const initial = activeMember.name?.charAt(0)?.toUpperCase() || "?";
  const hasAllergies = activeMember.allergies && activeMember.allergies.length > 0;
  const hasConditions = activeMember.chronic_conditions && activeMember.chronic_conditions.length > 0;
  const hasMeds = activeMedicines.length > 0;
  const hasEmergencyContact = !!activeMember.emergency_contact_phone;

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <AppHeader title="Emergency Card" showBack />

      <main className="flex-1 px-4 py-4 pb-32 space-y-4 max-w-lg mx-auto w-full">
        {/* Member pills */}
        {members.length > 1 && (
          <div className="flex gap-2 overflow-x-auto -mx-1 px-1 pb-1 no-scrollbar">
            {members.map((m) => {
              const isActive = m.id === (activeMember?.id || "");
              const memberInitial = m.name?.charAt(0)?.toUpperCase() || "?";
              return (
                <button
                  key={m.id}
                  onClick={() => setSelectedMemberId(m.id)}
                  className={`flex items-center gap-2 shrink-0 rounded-full pl-1 pr-3 py-1 border transition-all ${
                    isActive
                      ? "bg-red-600 border-red-600 text-white shadow-md scale-105"
                      : "bg-background border-border hover:border-red-300"
                  }`}
                >
                  <div
                    className={`h-7 w-7 rounded-full flex items-center justify-center text-xs font-bold ${
                      isActive
                        ? "bg-white text-red-600"
                        : "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-400"
                    }`}
                  >
                    {memberInitial}
                  </div>
                  <span className="text-xs font-medium whitespace-nowrap">{m.name}</span>
                </button>
              );
            })}
          </div>
        )}

        {/* ─── Full Emergency Card ───────────────────────────────────── */}
        <Card className="overflow-hidden border-2 border-red-500 shadow-lg">
          {/* Red header */}
          <div className="bg-gradient-to-r from-red-600 to-red-700 px-4 py-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Shield className="h-4 w-4 text-white" />
              <span className="text-white font-bold text-xs tracking-widest uppercase">
                Emergency Health Card
              </span>
            </div>
            <button
              onClick={() => setShowQR(true)}
              className="h-7 w-7 rounded-full bg-white/20 flex items-center justify-center hover:bg-white/30 transition"
            >
              <QrCode className="h-3.5 w-3.5 text-white" />
            </button>
          </div>

          <CardContent className="p-0">
            {/* Identity + blood group */}
            <div className="flex items-center gap-3 px-4 py-4">
              <div className="h-14 w-14 rounded-full bg-gradient-to-br from-red-500 to-red-700 flex items-center justify-center text-white text-xl font-bold shadow-md shrink-0">
                {initial}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xl font-bold leading-tight truncate">{activeMember.name}</p>
                <div className="flex items-center gap-2 mt-0.5 text-xs text-muted-foreground">
                  <span>{formatRelation(activeMember.relation)}</span>
                  {age !== null && (
                    <>
                      <span>·</span>
                      <span>{age} yrs</span>
                    </>
                  )}
                  {activeMember.gender && (
                    <>
                      <span>·</span>
                      <span>{formatGender(activeMember.gender)}</span>
                    </>
                  )}
                </div>
              </div>
              {activeMember.blood_group && (
                <div className="h-14 w-14 rounded-2xl bg-red-600 flex flex-col items-center justify-center shadow-lg shrink-0">
                  <span className="text-white text-lg font-black leading-none">
                    {activeMember.blood_group}
                  </span>
                  <span className="text-white/70 text-[8px] font-bold uppercase mt-0.5">Blood</span>
                </div>
              )}
            </div>

            {/* Allergies */}
            {hasAllergies && (
              <div className="px-4 py-3 bg-red-50 dark:bg-red-950/30 border-t border-red-200 dark:border-red-800">
                <div className="flex items-center gap-2 mb-2">
                  <AlertTriangle className="h-4 w-4 text-red-600" />
                  <span className="text-xs font-bold text-red-700 dark:text-red-400 uppercase tracking-wide">
                    Allergies
                  </span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {activeMember.allergies.map((a, i) => (
                    <span key={i} className="px-2.5 py-1 rounded-full bg-red-600 text-white text-xs font-semibold">
                      {a}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Chronic conditions */}
            {hasConditions && (
              <div className="px-4 py-3 bg-orange-50 dark:bg-orange-950/20 border-t border-orange-200 dark:border-orange-800">
                <div className="flex items-center gap-2 mb-2">
                  <Heart className="h-4 w-4 text-orange-600" />
                  <span className="text-xs font-bold text-orange-700 dark:text-orange-400 uppercase tracking-wide">
                    Chronic Conditions
                  </span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {activeMember.chronic_conditions.map((c, i) => (
                    <span key={i} className="px-2.5 py-1 rounded-full bg-orange-100 dark:bg-orange-900/40 text-orange-800 dark:text-orange-300 text-xs font-medium border border-orange-200 dark:border-orange-800">
                      {c}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Current medicines */}
            <div className="px-4 py-3 border-t border-border">
              <div className="flex items-center gap-2 mb-2">
                <Pill className="h-4 w-4 text-blue-600" />
                <span className="text-xs font-bold text-blue-700 dark:text-blue-400 uppercase tracking-wide">
                  Current Medicines
                </span>
              </div>
              {hasMeds ? (
                <div className="space-y-1.5">
                  {activeMedicines.map((med) => (
                    <div key={med.id} className="flex items-center justify-between text-sm bg-blue-50 dark:bg-blue-950/20 rounded-lg px-3 py-2">
                      <span className="font-medium truncate">{med.name}</span>
                      <span className="text-muted-foreground text-xs shrink-0 ml-2">
                        {[med.dosage, med.frequency?.replace("_", " ")].filter(Boolean).join(" · ")}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">No active medicines</p>
              )}
            </div>

            {/* Emergency contact — tap to call */}
            {hasEmergencyContact && (
              <a
                href={`tel:${activeMember.emergency_contact_phone}`}
                className="flex items-center justify-between px-4 py-3 bg-green-50 dark:bg-green-950/20 border-t border-green-200 dark:border-green-800 active:bg-green-100 dark:active:bg-green-950/40 transition-colors"
              >
                <div>
                  <span className="text-xs font-bold text-green-700 dark:text-green-400 uppercase tracking-wide">
                    Emergency Contact
                  </span>
                  <p className="text-sm font-medium mt-0.5">
                    {activeMember.emergency_contact_name || "Contact"} · {activeMember.emergency_contact_phone}
                  </p>
                </div>
                <div className="bg-green-600 text-white rounded-full p-2.5 shrink-0 shadow-md">
                  <Phone className="h-5 w-5" />
                </div>
              </a>
            )}

            {/* ABHA ID if present */}
            {activeMember.abha_number && (
              <div className="px-4 py-2.5 border-t border-border bg-muted/30">
                <div className="flex items-center gap-2">
                  <Shield className="h-3.5 w-3.5 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">
                    ABHA: <span className="font-mono font-medium">{activeMember.abha_number}</span>
                  </span>
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Action row */}
        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={() => router.push(`/family/${activeMember.id}/edit`)}
            className="flex items-center justify-center gap-2 h-11 rounded-xl border border-border bg-background hover:bg-muted/50 text-sm font-medium transition"
          >
            <Pencil className="h-4 w-4" />
            Edit Info
          </button>
          <button
            onClick={() => setShowQR(true)}
            className="flex items-center justify-center gap-2 h-11 rounded-xl border border-border bg-background hover:bg-muted/50 text-sm font-medium transition"
          >
            <QrCode className="h-4 w-4" />
            Show QR Code
          </button>
        </div>

        {/* Completeness hint */}
        {(!activeMember.blood_group || !hasAllergies || !hasEmergencyContact) && (
          <div className="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-xl p-3">
            <p className="text-xs font-medium text-amber-800 dark:text-amber-300 mb-1">
              Complete your card for emergencies:
            </p>
            <ul className="text-xs text-amber-700 dark:text-amber-400 space-y-0.5">
              {!activeMember.blood_group && <li>+ Add blood group</li>}
              {!hasAllergies && <li>+ Add allergies (or mark "None")</li>}
              {!hasEmergencyContact && <li>+ Add emergency contact</li>}
            </ul>
          </div>
        )}

        <div className="text-center pt-2">
          <p className="text-[11px] text-muted-foreground">
            Powered by <span className="font-semibold text-red-600">MediFamily</span>
          </p>
        </div>
      </main>

      {/* Sticky share */}
      <div className="fixed bottom-20 left-0 right-0 px-4 z-10 pointer-events-none">
        <div className="max-w-lg mx-auto pointer-events-auto">
          <Button
            onClick={handleShareCard}
            className="w-full h-12 bg-red-600 hover:bg-red-700 text-white shadow-2xl shadow-red-600/30 rounded-full font-semibold"
          >
            <Share2 className="h-5 w-5 mr-2" />
            Share via WhatsApp
          </Button>
        </div>
      </div>

      {/* QR Modal */}
      {showQR && (
        <div
          onClick={() => setShowQR(false)}
          className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in duration-200"
        >
          <div
            onClick={(e) => e.stopPropagation()}
            className="relative bg-white dark:bg-zinc-900 rounded-3xl p-6 max-w-sm w-full shadow-2xl animate-in zoom-in-95 duration-200"
          >
            <button
              onClick={() => setShowQR(false)}
              className="absolute top-3 right-3 h-9 w-9 rounded-full bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 flex items-center justify-center transition"
              aria-label="Close"
            >
              <X className="h-4 w-4" />
            </button>

            <div className="text-center mb-4">
              <div className="inline-flex items-center gap-1.5 mb-2">
                <Shield className="h-4 w-4 text-red-600" />
                <span className="text-[10px] uppercase tracking-widest font-bold text-red-600">
                  Emergency Card
                </span>
              </div>
              <h2 className="text-xl font-bold">{activeMember.name}</h2>
              <p className="text-xs text-muted-foreground mt-0.5">
                {[
                  activeMember.blood_group,
                  age !== null ? `${age} yrs` : null,
                  activeMember.gender ? formatGender(activeMember.gender) : null,
                ]
                  .filter(Boolean)
                  .join(" · ")}
              </p>
            </div>

            <div className="bg-white p-4 rounded-2xl border-2 border-red-100 mb-4 flex items-center justify-center">
              <QRCodeSVG
                value={buildShareText()}
                size={240}
                level="M"
                marginSize={2}
              />
            </div>

            <p className="text-center text-xs text-muted-foreground mb-3">
              Show this QR to doctors or hospital staff in emergencies
            </p>

            <Button
              onClick={() => { setShowQR(false); handleShareCard(); }}
              className="w-full bg-red-600 hover:bg-red-700 text-white"
            >
              <Share2 className="h-4 w-4 mr-2" />
              Share as Text
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

